### ISSUE TITLE
How to setup if I want to use rime-bopomofo

### ISSUE THREAD

**Issue by tsoua2** [ScriptGo/rime#1]
Please advise how to config rime for bopomofo IME?

**Comment by tsoua2** [comment]
我按照[對照表](https://gist.github.com/BruceLEO1969/1dcc1323dda33a6c4624)設定好bopomofo IME

**Comment by ScriptGo** [comment]
> 我按照[對照表](https://gist.github.com/BruceLEO1969/1dcc1323dda33a6c4624)設定好bopomofo IME

参考一下官方的文档试试， https://github.com/rime/rime-bopomofo 我没用过注音输入法
